### ISSUE TITLE
Did you test your setup (NanoPi Neo) with Windows 10 Host or Linux?

### ISSUE THREAD

**Issue by xbing6** [parkrrrr/bdio#13]
This is awesome project. One question: did you test your setup (NanoPi Neo) with Windows 10 Host or Linux like Ubuntu?

I understand you connected HIMS SyncBraille to NanoPi Neo.

**Comment by parkrrrr** [comment]
I'm not exactly sure what question you're asking, but I'll try to answer.

The NanoPi Neo is sort of an intermediary in this project. It acts as a USB host for the SyncBraille, and as a USB device for another computer. The SyncBraille internally uses an FTDI FT232 USB-to-serial chip, so it looks like a serial port if you plug it directly into your host computer. Putting the NanoPi running this software in the middle makes it look like a modern Braille display that speaks HUTRR-78. Currently, there's little to no advantage to this, but the vision for the future is that you'll be able to just plug it in and your screen reader will automatically recognize it and know how many cells and what buttons it has. 

**The NanoPi runs a custom build of OpenWRT, which is based on Linux** and designed for smaller embedded systems like wifi routers and such. Once the software is installed, ideally, you never have to worry about what's running on the Neo, because it just works. (It's not to that point, yet, because I haven't been able to find the time to do any development work on it since the pandemic started.)

**The other computer, the one that you would be interacting with in normal use, runs whatever OS you like.** You plug the Braille display into the USB-A port on the Neo, and you plug a cable into the USB-OTG port on the Neo and the USB-A port on your desktop or laptop computer, and as far as the desktop computer knows it's plugged directly into a Braille display that supports HID Braille. In my case, **all of my tests have been with a Windows 10 host** running custom HID Braille software that I can't release, but the host is mostly irrelevant as long as the software knows how to work with HUTRR-78/HID Braille.

Note that as far as I know, there is little to no support in current screen readers for HID Braille - that's one of the reasons I started this project: to try to break the logjam of "there's no software support so why create hardware / there's no hardware so why add this feature to our software" that's been pervading the AT market. Also, I don't know if screen readers that do support HID Braille will work properly if they get attached to a device they weren't expecting; it all depends on how they implement their drivers. Current screen readers have databases of what keys are available on a given device and what mappings to use for them, for example, so they might attempt to do a database lookup with the manufacturer/model strings and fail if they're not found. We'll all just have to wait and see how that shakes out.

**Comment by parkrrrr** [comment]
(Note: I'm going to attempt to convert this issue to a discussion, since it's not an action item, so it may look like it's been deleted from the Issues view.)
